export class TaskForgeError extends Error {
  constructor(
    public code: string,
    message: string,
  ) {
    super(message);
    this.name = 'TaskForgeError';
  }
}

export const ErrorCodes = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  BLOCKERS_INCOMPLETE: 'BLOCKERS_INCOMPLETE',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  NOT_IN_REVIEW: 'NOT_IN_REVIEW',
  INVALID_PARENT: 'INVALID_PARENT',
  SUBTASK_DEPTH_EXCEEDED: 'SUBTASK_DEPTH_EXCEEDED',
  CONFLICT_VERSION_MISMATCH: 'CONFLICT_VERSION_MISMATCH',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ALREADY_ARCHIVED: 'ALREADY_ARCHIVED',
  SOFT_DELETED: 'SOFT_DELETED',
  RECURRENCE_INVALID: 'RECURRENCE_INVALID',
  OWNER_EXISTS: 'OWNER_EXISTS',
  WORKSPACE_EXISTS: 'WORKSPACE_EXISTS',
} as const;
