use crate::hooks::{HookEngine, HookResult};
use crate::model::{DueStrategy, Recurrence, RecurrenceFrequency, Task, TaskStatus};
use crate::store::{AuditEntry, TaskStore};
use crate::transition::can_transition;

/// A domain error, carrying the stable code the CLI reports in its JSON envelope.
#[derive(Debug, thiserror::Error)]
pub enum TaskError {
    #[error("task not found: {0}")]
    NotFound(String),
    #[error("cannot move {id} from {from} to {to}")]
    InvalidTransition {
        id: String,
        from: TaskStatus,
        to: TaskStatus,
    },
    #[error("{id} is blocked by unresolved task(s): {blockers}")]
    Blocked { id: String, blockers: String },
    #[error("{0} requires review; request review instead of completing it directly")]
    ReviewRequired(String),
    #[error("{id} is at version {actual}, not {expected}; re-read and retry")]
    VersionMismatch {
        id: String,
        expected: i64,
        actual: i64,
    },
    #[error("could not write {id}: {source}")]
    Io { id: String, source: std::io::Error },
}

impl TaskError {
    /// The stable machine-readable code. Kept identical to the documented set so existing
    /// agent error handling keeps working across the rewrite.
    pub fn code(&self) -> &'static str {
        match self {
            TaskError::NotFound(_) => "TASK_NOT_FOUND",
            TaskError::InvalidTransition { .. } => "INVALID_STATUS_TRANSITION",
            TaskError::Blocked { .. } => "BLOCKED_BY_OPEN_TASK",
            TaskError::ReviewRequired(_) => "REVIEW_REQUIRED",
            TaskError::VersionMismatch { .. } => "CONFLICT_VERSION_MISMATCH",
            TaskError::Io { .. } => "IO_ERROR",
        }
    }
}

/// A problem that happened *after* a mutation was already committed.
///
/// It cannot be an error — the change is real and the caller must be told it happened — but it
/// must not be silent either, or an agent believes a notification fired or an audit entry
/// landed when neither did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Warning {
    pub code: &'static str,
    pub message: String,
}

/// Workflow operations over a store.
///
/// `now` is injected rather than read from the clock so every timestamp assertion in the
/// tests is exact instead of approximate.
pub struct TaskService<S: TaskStore> {
    pub store: S,
    now: String,
    /// Id of the occurrence generated by the most recent completion, if any. Recorded so a
    /// caller (and the tests) can report the follow-on task without re-scanning the store.
    pub last_generated: Option<String>,
    /// Hooks to announce committed mutations to. `None` means none are configured, which is
    /// the common case and must stay free of cost.
    hooks: Option<HookEngine>,
    /// Outcome of the hooks fired by the most recent mutation. The CLI turns any failure among
    /// these into an envelope warning.
    pub last_hook_results: Vec<HookResult>,
    /// Post-commit problems from the most recent mutation, for the caller to report.
    pub last_warnings: Vec<Warning>,
}

impl<S: TaskStore> TaskService<S> {
    pub fn new(store: S, now: impl Into<String>) -> Self {
        TaskService {
            store,
            now: now.into(),
            last_generated: None,
            hooks: None,
            last_hook_results: Vec::new(),
            last_warnings: Vec::new(),
        }
    }

    /// Attach a hook engine. Hooks fire only after a mutation is committed, and never gate it.
    pub fn with_hooks(mut self, engine: HookEngine) -> Self {
        self.hooks = Some(engine);
        self
    }

    /// Move a task to a new status, enforcing the transition table, blockers, the review
    /// gate, and optimistic concurrency — in that order, so the most specific complaint wins.
    pub fn set_status(
        &mut self,
        id: &str,
        to: TaskStatus,
        actor: &str,
        expected_version: Option<i64>,
    ) -> Result<Task, TaskError> {
        let mut task = self
            .store
            .get(id)
            .ok_or_else(|| TaskError::NotFound(id.to_string()))?;

        if let Some(expected) = expected_version {
            if expected != task.version {
                return Err(TaskError::VersionMismatch {
                    id: id.to_string(),
                    expected,
                    actual: task.version,
                });
            }
        }

        let from = task.status;
        if !can_transition(from, to) {
            return Err(TaskError::InvalidTransition {
                id: id.to_string(),
                from,
                to,
            });
        }

        // Completing without review is only legitimate when no review was demanded.
        if to == TaskStatus::Done && task.review_required && from != TaskStatus::Merged {
            return Err(TaskError::ReviewRequired(id.to_string()));
        }

        // Dispatching work requires every dependency to be genuinely finished. `Merged` does
        // not qualify: it still awaits acceptance.
        if to == TaskStatus::Running {
            let unresolved: Vec<String> = task
                .blocked_by
                .iter()
                .filter(|b| {
                    self.store
                        .get(b)
                        .map(|t| t.status != TaskStatus::Done)
                        .unwrap_or(true)
                })
                .cloned()
                .collect();
            if !unresolved.is_empty() {
                return Err(TaskError::Blocked {
                    id: id.to_string(),
                    blockers: unresolved.join(", "),
                });
            }
        }

        task.status = to;
        task.updated_at = self.now.clone();
        task.version += 1;
        match to {
            TaskStatus::Done => task.completed_at = Some(self.now.clone()),
            TaskStatus::InReview => task.review_requested_at = Some(self.now.clone()),
            _ => {}
        }

        self.last_warnings.clear();

        // The one write whose failure is fatal: until this lands, nothing has happened, and
        // reporting success would hand the caller a status that is not stored.
        self.store.put(task.clone()).map_err(|e| TaskError::Io {
            id: id.to_string(),
            source: e,
        })?;

        // Everything below runs after the change is committed, so no failure here can un-commit
        // it. Each is therefore a warning: real, reported, and not an error.
        if let Err(e) = self.store.append_audit(AuditEntry {
            ts: self.now.clone(),
            actor: actor.to_string(),
            action: "status_changed".to_string(),
            task_id: id.to_string(),
            from: Some(from.to_string()),
            to: Some(to.to_string()),
        }) {
            self.last_warnings.push(Warning {
                code: "AUDIT_WRITE_FAILED",
                message: format!("{id} moved to {to} but the audit entry was not written: {e}"),
            });
        }

        self.last_hook_results = match &self.hooks {
            Some(engine) => engine.fire("task.status_changed", &task.workspace, id, to.as_str()),
            None => Vec::new(),
        };

        // A recurring task that reaches Done spawns its successor, so "later" is scheduled
        // rather than remembered.
        self.last_generated = None;
        if to == TaskStatus::Done {
            if let Some(rec) = task.recurrence.clone() {
                match self.generate_next_occurrence(&task, &rec, actor) {
                    Ok(next) => self.last_generated = Some(next),
                    Err(e) => self.last_warnings.push(Warning {
                        code: "RECURRENCE_WRITE_FAILED",
                        message: format!(
                            "{id} completed but its next occurrence was not created: {e}"
                        ),
                    }),
                }
            }
        }
        Ok(task)
    }

    /// Create the follow-on occurrence of a completed recurring task.
    ///
    /// Fallible so a failure to store the successor is reported rather than announced as an id
    /// that was never written.
    fn generate_next_occurrence(
        &mut self,
        prior: &Task,
        rec: &Recurrence,
        actor: &str,
    ) -> std::io::Result<String> {
        let id = self.store.allocate_id();
        let mut next = Task::new(
            &id,
            &prior.title,
            &prior.workspace,
            &prior.owner,
            self.now.clone(),
        );

        if rec.carry_forward_description {
            next.description = prior.description.clone();
        }
        if rec.preserve_review_required {
            next.review_required = prior.review_required;
            next.reviewer = prior.reviewer.clone();
        }
        if !rec.carry_forward_owner {
            next.owner = String::new();
        }
        next.prior_occurrence_id = Some(prior.id.clone());
        // The schedule itself carries forward, or the task would recur exactly once.
        next.recurrence = Some(rec.clone());
        next.due_at = self.next_due(prior, rec);

        self.store.put(next)?;
        self.store.append_audit(AuditEntry {
            ts: self.now.clone(),
            actor: actor.to_string(),
            action: "recurrence_generated".to_string(),
            task_id: id.clone(),
            from: Some(prior.id.clone()),
            to: None,
        })?;
        Ok(id)
    }

    /// Due date for the next occurrence, per the configured strategy.
    ///
    /// `None` means "do not carry a due date forward" and is also the answer when the prior
    /// task had no due date to advance, or when its timestamp cannot be parsed — an
    /// unparseable date must not become a panic in the middle of a completion.
    fn next_due(&self, prior: &Task, rec: &Recurrence) -> Option<String> {
        if rec.carry_forward_due_strategy == DueStrategy::None {
            return None;
        }
        let prior_due = prior.due_at.as_deref()?;
        let base = match rec.carry_forward_due_strategy {
            DueStrategy::Relative => &self.now,
            _ => prior_due,
        };
        advance(base, rec.frequency, rec.interval)
    }
}

/// Add `interval` periods of `frequency` to an RFC3339 timestamp.
///
/// Month arithmetic clamps to the last valid day of the target month: 31 January plus one
/// month is 28 February, not 3 March. JavaScript's `setMonth` overflows instead, so this is a
/// deliberate divergence from the implementation being replaced — silently skipping a month is
/// a worse answer for a recurring task than landing on its final day.
fn advance(ts: &str, freq: RecurrenceFrequency, interval: u32) -> Option<String> {
    use time::format_description::well_known::Rfc3339;
    let start = time::OffsetDateTime::parse(ts, &Rfc3339).ok()?;
    let n = interval as i64;
    let moved = match freq {
        RecurrenceFrequency::Hourly => start.checked_add(time::Duration::hours(n))?,
        RecurrenceFrequency::Daily => start.checked_add(time::Duration::days(n))?,
        RecurrenceFrequency::Weekly => start.checked_add(time::Duration::weeks(n))?,
        RecurrenceFrequency::Monthly => {
            let months_total = start.month() as i32 - 1 + interval as i32;
            let year = start.year() + months_total / 12;
            let month = time::Month::try_from((months_total % 12 + 1) as u8).ok()?;
            let last = time::util::days_in_month(month, year);
            let day = start.day().min(last);
            // Step to day 1 before changing month: replacing the month while the day is
            // still 31 is rejected outright for a short target month.
            start
                .replace_day(1)
                .ok()?
                .replace_year(year)
                .ok()?
                .replace_month(month)
                .ok()?
                .replace_day(day)
                .ok()?
        }
    };
    moved.format(&Rfc3339).ok()
}

#[cfg(test)]
mod tests {
    use crate::model::{DueStrategy, Recurrence, RecurrenceFrequency, Task, TaskStatus};
    use crate::service::*;
    use crate::store::MemoryStore;

    fn task(id: &str) -> Task {
        Task::new(id, "t", "main", "agent", "2026-09-01T00:00:00Z")
    }

    fn svc() -> TaskService<MemoryStore> {
        TaskService::new(MemoryStore::new(), "2026-09-02T00:00:00Z")
    }

    #[test]
    fn start_refuses_while_a_blocker_is_unresolved() {
        let mut s = svc();
        s.store.put(task("TASK-0002")).unwrap();
        let mut t = task("TASK-0001");
        t.blocked_by = vec!["TASK-0002".into()];
        s.store.put(t).unwrap();

        let err = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "BLOCKED_BY_OPEN_TASK", "got: {err}");
        assert!(
            err.to_string().contains("TASK-0002"),
            "names the blocker: {err}"
        );
    }

    #[test]
    fn start_proceeds_once_every_blocker_is_done() {
        let mut s = svc();
        let mut b = task("TASK-0002");
        b.status = TaskStatus::Done;
        s.store.put(b).unwrap();
        let mut t = task("TASK-0001");
        t.blocked_by = vec!["TASK-0002".into()];
        s.store.put(t).unwrap();

        let out = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap();
        assert_eq!(out.status, TaskStatus::Running);
        assert_eq!(out.version, 2, "a mutation bumps the version");
        assert_eq!(out.updated_at, "2026-09-02T00:00:00Z");
    }

    #[test]
    fn a_merged_blocker_does_not_count_as_resolved() {
        // Merged awaits acceptance. Letting a dependent start on it is exactly the
        // premature-completion mistake the eleven-state model exists to prevent.
        let mut s = svc();
        let mut b = task("TASK-0002");
        b.status = TaskStatus::Merged;
        s.store.put(b).unwrap();
        let mut t = task("TASK-0001");
        t.blocked_by = vec!["TASK-0002".into()];
        s.store.put(t).unwrap();

        let err = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "BLOCKED_BY_OPEN_TASK");
    }

    #[test]
    fn an_illegal_transition_is_rejected_by_code() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap(); // Open
        let err = s
            .set_status("TASK-0001", TaskStatus::Merged, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "INVALID_STATUS_TRANSITION", "got: {err}");
    }

    #[test]
    fn completing_a_review_required_task_directly_is_refused() {
        let mut s = svc();
        let mut t = task("TASK-0001");
        t.status = TaskStatus::Running;
        t.review_required = true;
        s.store.put(t).unwrap();

        let err = s
            .set_status("TASK-0001", TaskStatus::Done, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "REVIEW_REQUIRED", "got: {err}");
    }

    #[test]
    fn a_stale_version_is_a_conflict() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap(); // version 1
        let err = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", Some(99))
            .unwrap_err();
        assert_eq!(err.code(), "CONFLICT_VERSION_MISMATCH", "got: {err}");
    }

    #[test]
    fn the_matching_version_is_accepted() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        assert!(s
            .set_status("TASK-0001", TaskStatus::Running, "agent", Some(1))
            .is_ok());
    }

    #[test]
    fn an_unknown_task_is_reported_not_created() {
        let mut s = svc();
        let err = s
            .set_status("TASK-9999", TaskStatus::Running, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "TASK_NOT_FOUND");
    }

    #[test]
    fn reaching_done_stamps_completed_at() {
        let mut s = svc();
        let mut t = task("TASK-0001");
        t.status = TaskStatus::Running;
        s.store.put(t).unwrap();
        let out = s
            .set_status("TASK-0001", TaskStatus::Done, "agent", None)
            .unwrap();
        assert_eq!(out.completed_at.as_deref(), Some("2026-09-02T00:00:00Z"));
    }

    #[test]
    fn entering_review_stamps_the_request_time() {
        let mut s = svc();
        let mut t = task("TASK-0001");
        t.status = TaskStatus::Running;
        t.review_required = true;
        s.store.put(t).unwrap();
        let out = s
            .set_status("TASK-0001", TaskStatus::InReview, "agent", None)
            .unwrap();
        assert_eq!(
            out.review_requested_at.as_deref(),
            Some("2026-09-02T00:00:00Z")
        );
    }

    #[test]
    fn every_mutation_appends_one_audit_entry() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.set_status("TASK-0001", TaskStatus::Running, "aaron", None)
            .unwrap();
        let log = s.store.audit_of("TASK-0001");
        assert_eq!(log.len(), 1, "one entry per mutation");
        assert_eq!(log[0].actor, "aaron");
        assert_eq!(log[0].action, "status_changed");
    }

    fn recurring(
        id: &str,
        freq: RecurrenceFrequency,
        due: Option<&str>,
        strat: DueStrategy,
    ) -> Task {
        let mut t = task(id);
        t.status = TaskStatus::Running;
        t.due_at = due.map(String::from);
        t.recurrence = Some(Recurrence {
            frequency: freq,
            interval: 1,
            preserve_review_required: true,
            carry_forward_description: true,
            carry_forward_owner: true,
            carry_forward_due_strategy: strat,
        });
        t
    }

    #[test]
    fn completing_a_recurring_task_generates_a_linked_next_occurrence() {
        let mut s = svc();
        let mut t = recurring(
            "TASK-0001",
            RecurrenceFrequency::Daily,
            None,
            DueStrategy::None,
        );
        t.description = Some("water the plants".into());
        s.store.put(t).unwrap();

        let done = s
            .set_status("TASK-0001", TaskStatus::Done, "aaron", None)
            .unwrap();
        assert_eq!(done.status, TaskStatus::Done);

        let next = s
            .last_generated
            .clone()
            .expect("a next occurrence was created");
        let n = s.store.get(&next).expect("and stored");
        assert_ne!(n.id, "TASK-0001", "it is a new task");
        assert_eq!(
            n.prior_occurrence_id.as_deref(),
            Some("TASK-0001"),
            "linked to its predecessor"
        );
        assert_eq!(
            n.status,
            TaskStatus::Open,
            "the new occurrence starts fresh"
        );
        assert_eq!(
            n.description.as_deref(),
            Some("water the plants"),
            "description carried"
        );
        assert!(
            n.recurrence.is_some(),
            "the schedule carries forward, or it recurs once"
        );
    }

    #[test]
    fn completing_a_non_recurring_task_generates_nothing() {
        let mut s = svc();
        let mut t = task("TASK-0001");
        t.status = TaskStatus::Running;
        s.store.put(t).unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "aaron", None)
            .unwrap();
        assert!(s.last_generated.is_none());
    }

    #[test]
    fn carry_forward_flags_are_respected_when_false() {
        let mut s = svc();
        let mut t = recurring(
            "TASK-0001",
            RecurrenceFrequency::Daily,
            None,
            DueStrategy::None,
        );
        t.description = Some("dropped".into());
        t.review_required = true;
        if let Some(r) = t.recurrence.as_mut() {
            r.carry_forward_description = false;
            r.preserve_review_required = false;
        }
        s.store.put(t).unwrap();

        // review_required means Done is only reachable via review, so walk the real path
        // rather than asserting against a shortcut the service correctly refuses.
        for to in [TaskStatus::InReview, TaskStatus::Merged, TaskStatus::Done] {
            s.set_status("TASK-0001", to, "aaron", None).unwrap();
        }
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert!(n.description.is_none(), "description not carried");
        assert!(!n.review_required, "review requirement not preserved");
    }

    #[test]
    fn due_strategy_none_leaves_the_next_occurrence_undated() {
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Daily,
                Some("2026-09-01T00:00:00Z"),
                DueStrategy::None,
            ))
            .unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert!(n.due_at.is_none());
    }

    #[test]
    fn due_strategy_absolute_advances_from_the_previous_due_date() {
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Daily,
                Some("2026-09-01T08:00:00Z"),
                DueStrategy::Absolute,
            ))
            .unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert_eq!(n.due_at.as_deref(), Some("2026-09-02T08:00:00Z"));
    }

    #[test]
    fn due_strategy_relative_advances_from_completion_time() {
        // `now` for this service is 2026-09-02T00:00:00Z.
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Weekly,
                Some("2026-01-01T00:00:00Z"),
                DueStrategy::Relative,
            ))
            .unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert_eq!(
            n.due_at.as_deref(),
            Some("2026-09-09T00:00:00Z"),
            "one week past now"
        );
    }

    #[test]
    fn hourly_and_monthly_intervals_advance_correctly() {
        for (freq, due, expected) in [
            (
                RecurrenceFrequency::Hourly,
                "2026-09-01T23:00:00Z",
                "2026-09-02T00:00:00Z",
            ),
            (
                RecurrenceFrequency::Monthly,
                "2026-09-30T00:00:00Z",
                "2026-10-30T00:00:00Z",
            ),
        ] {
            let mut s = svc();
            s.store
                .put(recurring(
                    "TASK-0001",
                    freq,
                    Some(due),
                    DueStrategy::Absolute,
                ))
                .unwrap();
            s.set_status("TASK-0001", TaskStatus::Done, "a", None)
                .unwrap();
            let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
            assert_eq!(n.due_at.as_deref(), Some(expected), "{freq:?}");
        }
    }

    #[test]
    fn a_monthly_rollover_clamps_to_the_last_valid_day() {
        // Jan 31 + 1 month has no equivalent day. JavaScript's setMonth overflows this into
        // March; clamping to the end of February is the deliberate divergence.
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Monthly,
                Some("2026-01-31T12:00:00Z"),
                DueStrategy::Absolute,
            ))
            .unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert_eq!(n.due_at.as_deref(), Some("2026-02-28T12:00:00Z"));
    }

    #[test]
    fn a_status_change_fires_the_status_changed_hook_once() {
        let d = tempfile::tempdir().unwrap();
        let out = d.path().join("fired");
        let engine = crate::hooks::HookEngine::new(vec![crate::hooks::HookConfig {
            id: "capture".into(),
            enabled: true,
            event: "task.status_changed".into(),
            command: "sh".into(),
            args: vec!["-c".into(), format!("cat >> {}", out.display())],
            workspace_filter: None,
            timeout_ms: 5_000,
        }]);
        let mut s = TaskService::new(MemoryStore::new(), "2026-09-02T00:00:00Z").with_hooks(engine);
        s.store.put(task("TASK-0001")).unwrap();

        s.set_status("TASK-0001", TaskStatus::Running, "aaron", None)
            .unwrap();

        let body = std::fs::read_to_string(&out).expect("the hook ran and wrote its stdin");
        let v: serde_json::Value = serde_json::from_str(body.trim()).expect("payload is JSON");
        assert_eq!(v["event"], "task.status_changed");
        assert_eq!(v["task_id"], "TASK-0001");
        assert_eq!(v["status"], "running", "the payload carries the NEW status");
    }

    #[test]
    fn a_refused_transition_fires_no_hook() {
        let d = tempfile::tempdir().unwrap();
        let out = d.path().join("fired");
        let engine = crate::hooks::HookEngine::new(vec![crate::hooks::HookConfig {
            id: "capture".into(),
            enabled: true,
            event: "task.status_changed".into(),
            command: "sh".into(),
            args: vec!["-c".into(), format!("cat >> {}", out.display())],
            workspace_filter: None,
            timeout_ms: 5_000,
        }]);
        let mut s = TaskService::new(MemoryStore::new(), "2026-09-02T00:00:00Z").with_hooks(engine);
        s.store.put(task("TASK-0001")).unwrap(); // Open

        // Open -> Merged is illegal, so nothing was committed and nothing should be announced.
        assert!(s
            .set_status("TASK-0001", TaskStatus::Merged, "aaron", None)
            .is_err());
        assert!(
            !out.exists(),
            "no hook may fire for a mutation that did not happen"
        );
    }

    #[test]
    fn a_failing_hook_does_not_roll_back_the_status_change() {
        let engine = crate::hooks::HookEngine::new(vec![crate::hooks::HookConfig {
            id: "bad".into(),
            enabled: true,
            event: "task.status_changed".into(),
            command: "false".into(),
            args: vec![],
            workspace_filter: None,
            timeout_ms: 5_000,
        }]);
        let mut s = TaskService::new(MemoryStore::new(), "2026-09-02T00:00:00Z").with_hooks(engine);
        s.store.put(task("TASK-0001")).unwrap();

        let out = s.set_status("TASK-0001", TaskStatus::Running, "aaron", None);
        assert!(
            out.is_ok(),
            "the mutation stands: hooks are notifications, not gates"
        );
        assert_eq!(
            s.store.get("TASK-0001").unwrap().status,
            TaskStatus::Running
        );
        assert_eq!(s.last_hook_results.len(), 1);
        assert!(!s.last_hook_results[0].ok, "but the failure is reported");
    }

    #[test]
    fn a_failed_task_write_is_reported_rather_than_reported_as_success() {
        // The defect this covers: `put` used to return `()`, so a full disk or a read-only
        // mount produced `ok: true` with a bumped version while the file on disk never moved.
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.store.fail_writes_now();

        let err = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap_err();
        assert_eq!(err.code(), "IO_ERROR", "got: {err}");
    }

    #[test]
    fn a_failed_task_write_leaves_the_stored_task_untouched() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.store.fail_writes_now();
        let _ = s.set_status("TASK-0001", TaskStatus::Running, "agent", None);

        let on_disk = s.store.get("TASK-0001").expect("still readable");
        assert_eq!(on_disk.status, TaskStatus::Open, "status did not move");
        assert_eq!(on_disk.version, 1, "and neither did the version");
    }

    #[test]
    fn a_failed_task_write_records_no_audit_entry_and_fires_no_hook() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.store.fail_writes_now();
        let _ = s.set_status("TASK-0001", TaskStatus::Running, "agent", None);

        assert!(
            s.store.audit_of("TASK-0001").is_empty(),
            "a change that did not commit is not history"
        );
        assert!(
            s.last_hook_results.is_empty(),
            "and must not be announced to hooks"
        );
    }

    #[test]
    fn a_failed_audit_append_still_commits_the_mutation() {
        // Asymmetric on purpose: the task write is the data, so its failure is fatal. The audit
        // append happens after the change is already committed, so failing it cannot un-commit
        // anything — reporting failure there would be a lie.
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.store.fail_audit_now();

        let out = s
            .set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .expect("the mutation stands");
        assert_eq!(out.status, TaskStatus::Running);
        assert_eq!(
            s.store.get("TASK-0001").unwrap().status,
            TaskStatus::Running,
            "and is on disk"
        );
    }

    #[test]
    fn a_failed_audit_append_is_reported_as_a_warning() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.store.fail_audit_now();
        s.set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap();

        assert_eq!(s.last_warnings.len(), 1, "the lost trail is surfaced");
        assert_eq!(s.last_warnings[0].code, "AUDIT_WRITE_FAILED");
    }

    #[test]
    fn a_successful_mutation_warns_about_nothing() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        s.set_status("TASK-0001", TaskStatus::Running, "agent", None)
            .unwrap();
        assert!(s.last_warnings.is_empty());
    }

    #[test]
    fn a_failed_successor_write_warns_without_failing_the_completion() {
        // The completion is committed before the successor is minted, so a write failure there
        // must not retroactively fail the completion the caller already observed.
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Daily,
                None,
                DueStrategy::None,
            ))
            .unwrap();
        // Allow the completion's own write, then fail — so only the successor cannot be stored.
        s.store.fail_writes_after(1);

        let out = s
            .set_status("TASK-0001", TaskStatus::Done, "agent", None)
            .expect("the completion stands");
        assert_eq!(out.status, TaskStatus::Done);
        assert!(s.last_generated.is_none(), "no successor to report");
        assert!(
            s.last_warnings
                .iter()
                .any(|w| w.code == "RECURRENCE_WRITE_FAILED"),
            "but the caller is told one was not created: {:?}",
            s.last_warnings
        );
    }

    #[test]
    fn a_service_without_hooks_configured_still_works() {
        let mut s = svc();
        s.store.put(task("TASK-0001")).unwrap();
        assert!(s
            .set_status("TASK-0001", TaskStatus::Running, "a", None)
            .is_ok());
        assert!(s.last_hook_results.is_empty());
    }

    #[test]
    fn an_unparseable_due_date_yields_no_due_date_rather_than_a_panic() {
        let mut s = svc();
        let mut t = recurring(
            "TASK-0001",
            RecurrenceFrequency::Daily,
            Some("not-a-timestamp"),
            DueStrategy::Absolute,
        );
        t.status = TaskStatus::Running;
        s.store.put(t).unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert!(
            n.due_at.is_none(),
            "a bad date is dropped, not propagated or panicked on"
        );
    }

    #[test]
    fn a_due_strategy_with_no_prior_due_date_carries_nothing() {
        let mut s = svc();
        s.store
            .put(recurring(
                "TASK-0001",
                RecurrenceFrequency::Daily,
                None,
                DueStrategy::Absolute,
            ))
            .unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert!(n.due_at.is_none());
    }

    #[test]
    fn carry_forward_owner_false_leaves_the_successor_unassigned() {
        let mut s = svc();
        let mut t = recurring(
            "TASK-0001",
            RecurrenceFrequency::Daily,
            None,
            DueStrategy::None,
        );
        if let Some(r) = t.recurrence.as_mut() {
            r.carry_forward_owner = false;
        }
        s.store.put(t).unwrap();
        s.set_status("TASK-0001", TaskStatus::Done, "a", None)
            .unwrap();
        let n = s.store.get(&s.last_generated.clone().unwrap()).unwrap();
        assert!(
            n.owner.is_empty(),
            "the successor needs assigning rather than inheriting"
        );
    }
}
